### PR TITLE
Added UID to Person object

### PR DESCRIPTION
**Pull request by ihappycoder**
Added `uid` field to Person object for cases where the app needs to store some internal information related to the specific contact. 

UID - The unique ID for this record. It’s guaranteed never to change, no matter how much the record changes. If you need to store a reference to a record, use this value. (https://developer.apple.com/documentation/addressbook/kabuidproperty?language=objc)

### CODE REVIEW

**Comment by ihappycoder** [comment]
Hi @ffflorian thanks for the review, just added `uid` reference to ts files with my latest commit

**Comment by ffflorian** [comment]
@ihappycoder thanks, I'll check with the team.

**Comment by marcoconti83** [comment]
Hi all,
Thanks for opening this PR! The code looks OK, but I'm missing a bit of context. Can you please add some context to the description of this PR? Why is this needed? What is UID? Was it tested? How?

**Comment by ihappycoder** [comment]
Hi @marcoconti83, updated PR description. We use this lib in out electron application to list contacts from address book, and users able to pin contacts on top in that list, so we need that uid to store it internally and then identify pinned contacts. Now we installing this lib via npm directly from the fork and it works well

**Comment by marcoconti83** [comment]
Thanks @ihappycoder !

**Comment by ffflorian** [comment]
Published in [`3.3.0`](https://github.com/wireapp/node-addressbook/releases/tag/v3.3.0), thanks @ihappycoder!

**Comment by ihappycoder** [comment]
> Published in [`3.3.0`](https://github.com/wireapp/node-addressbook/releases/tag/v3.3.0), thanks @ihappycoder!

Very nice to hear, thanks all! :)

**Pull request merged**
